services:
  server:
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    image: server
    container_name: mern-server-cont
    env_file:
      - ./server/.env.prod
    ports:
      - "3000:3000"  # Set explicitly
    environment:
      mongoDbUrl: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017
      mongoDbName: Shortify
      NODE_ENV: production
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - shortify
    stdin_open: true
    tty: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: mern-client-cont
    restart: always
    ports:
      - "80:80"  # React app on localhost:80
    depends_on:
      - server
    networks:
      - shortify

  mongodb:
    image: mongo
    container_name: mern-mongo-cont
    restart: unless-stopped
    ports:
      - "27018:27017"  # Avoids conflict with local MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - shortify-data:/data/db
    networks:
      - shortify

  mongo-express:
    image: mongo-express
    container_name: express-cont
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - shortify

volumes:
  shortify-data:

networks:
  shortify:
    driver: bridge
